contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #rnachrom channel"
    url: https://nfcore.slack.com/channels/rnachrom
    about: Discussion about the nf-core/rnachrom pipeline
